[package]
name = "io-pipe"
description = "This library add a thread safe way to create multi writers and single reader pipeline."
authors = ["Mnwa <nikhail@panfilov.tech>"]
version = "0.1.0"
edition = "2021"
categories = ["algorithms", "data-structures", "concurrency"]
license = "MIT"

[dependencies]
bytes = "1"
